<?php

namespace SunAsterisk\DomainVerifier\Tests\Strategies;

use PHPUnit\Framework\TestCase;
use SunAsterisk\DomainVerifier\Contracts\Models\DomainVerifiableInterface;
use SunAsterisk\DomainVerifier\Strategies\HTML;
use Mockery as m;
use SunAsterisk\DomainVerifier\Strategies\HTMLFile;

class HTMLFileTest extends TestCase
{
    protected $verification;
    protected $url;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->verification = new \stdClass();
        $this->verification->token = '123';

        $this->url = 'https://domain.local';
    }

    public function test_it_can_verify_html_file()
    {
        /** Mock DomainVerifiable*/
        $domainVerifiable = m::mock(DomainVerifiableInterface::class);
        $domainVerifiable->shouldReceive('getKey')->andReturns(123);

        /** Mock facade */
        m::mock('alias:\SunAsterisk\DomainVerifier\DomainVerificationFacade')
            ->shouldReceive('getTokenFor')
            ->andReturn($this->verification);

        /** @var HTML|m\MockInterface $strategy */
        $strategy = m::mock(HTMLFile::class)->makePartial()->shouldAllowMockingProtectedMethods();
        $strategy->shouldReceive('getToken')->with($this->url)->andReturn('123');
        $result = $strategy->verify($this->url, $domainVerifiable);

        $this->assertTrue($result);
    }
}
